// nitro's `static` preset defines no runtime entry of its own (a fully
// static build needs no server), but this nitro version still bundles a
// final "nitro" environment unconditionally and crashes if no entry is
// set (Vite falls back to index.html, which it refuses for an SSR
// consumer). This file is a harmless placeholder to satisfy that build
// step — it is never actually deployed or invoked. The real index.html
// is generated by scripts/generate-static-shell.mjs from the properly
// built SSR bundle instead.
export default {
  fetch: () => new Response(null, { status: 404 }),
};
