/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleInfoRouteImport } from './routes/vehicle-info'
import { Route as UserCreationRouteImport } from './routes/user-creation'
import { Route as TransitInfoRouteImport } from './routes/transit-info'
import { Route as TransitDamageInfoRouteImport } from './routes/transit-damage-info'
import { Route as ShipmentDetailsRouteImport } from './routes/shipment-details'
import { Route as ServiceLevelRouteImport } from './routes/service-level'
import { Route as SegmentInfoRouteImport } from './routes/segment-info'
import { Route as OrderInfoRouteImport } from './routes/order-info'
import { Route as InvoiceLoadDetailsRouteImport } from './routes/invoice-load-details'
import { Route as InsuranceClaimTrackingRouteImport } from './routes/insurance-claim-tracking'
import { Route as FreightBillingRouteImport } from './routes/freight-billing'
import { Route as DispatchOrdersRouteImport } from './routes/dispatch-orders'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsTransitEwayBillRouteImport } from './routes/reports.transit-eway-bill'
import { Route as ReportsPendingPodsRouteImport } from './routes/reports.pending-pods'
import { Route as ReportsFreightBillsRouteImport } from './routes/reports.freight-bills'

const VehicleInfoRoute = VehicleInfoRouteImport.update({
  id: '/vehicle-info',
  path: '/vehicle-info',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCreationRoute = UserCreationRouteImport.update({
  id: '/user-creation',
  path: '/user-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitInfoRoute = TransitInfoRouteImport.update({
  id: '/transit-info',
  path: '/transit-info',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitDamageInfoRoute = TransitDamageInfoRouteImport.update({
  id: '/transit-damage-info',
  path: '/transit-damage-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentDetailsRoute = ShipmentDetailsRouteImport.update({
  id: '/shipment-details',
  path: '/shipment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceLevelRoute = ServiceLevelRouteImport.update({
  id: '/service-level',
  path: '/service-level',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentInfoRoute = SegmentInfoRouteImport.update({
  id: '/segment-info',
  path: '/segment-info',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderInfoRoute = OrderInfoRouteImport.update({
  id: '/order-info',
  path: '/order-info',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceLoadDetailsRoute = InvoiceLoadDetailsRouteImport.update({
  id: '/invoice-load-details',
  path: '/invoice-load-details',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceClaimTrackingRoute = InsuranceClaimTrackingRouteImport.update({
  id: '/insurance-claim-tracking',
  path: '/insurance-claim-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightBillingRoute = FreightBillingRouteImport.update({
  id: '/freight-billing',
  path: '/freight-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchOrdersRoute = DispatchOrdersRouteImport.update({
  id: '/dispatch-orders',
  path: '/dispatch-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsTransitEwayBillRoute = ReportsTransitEwayBillRouteImport.update({
  id: '/reports/transit-eway-bill',
  path: '/reports/transit-eway-bill',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsPendingPodsRoute = ReportsPendingPodsRouteImport.update({
  id: '/reports/pending-pods',
  path: '/reports/pending-pods',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFreightBillsRoute = ReportsFreightBillsRouteImport.update({
  id: '/reports/freight-bills',
  path: '/reports/freight-bills',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-orders': typeof DispatchOrdersRoute
  '/freight-billing': typeof FreightBillingRoute
  '/insurance-claim-tracking': typeof InsuranceClaimTrackingRoute
  '/invoice-load-details': typeof InvoiceLoadDetailsRoute
  '/order-info': typeof OrderInfoRoute
  '/segment-info': typeof SegmentInfoRoute
  '/service-level': typeof ServiceLevelRoute
  '/shipment-details': typeof ShipmentDetailsRoute
  '/transit-damage-info': typeof TransitDamageInfoRoute
  '/transit-info': typeof TransitInfoRoute
  '/user-creation': typeof UserCreationRoute
  '/vehicle-info': typeof VehicleInfoRoute
  '/reports/freight-bills': typeof ReportsFreightBillsRoute
  '/reports/pending-pods': typeof ReportsPendingPodsRoute
  '/reports/transit-eway-bill': typeof ReportsTransitEwayBillRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-orders': typeof DispatchOrdersRoute
  '/freight-billing': typeof FreightBillingRoute
  '/insurance-claim-tracking': typeof InsuranceClaimTrackingRoute
  '/invoice-load-details': typeof InvoiceLoadDetailsRoute
  '/order-info': typeof OrderInfoRoute
  '/segment-info': typeof SegmentInfoRoute
  '/service-level': typeof ServiceLevelRoute
  '/shipment-details': typeof ShipmentDetailsRoute
  '/transit-damage-info': typeof TransitDamageInfoRoute
  '/transit-info': typeof TransitInfoRoute
  '/user-creation': typeof UserCreationRoute
  '/vehicle-info': typeof VehicleInfoRoute
  '/reports/freight-bills': typeof ReportsFreightBillsRoute
  '/reports/pending-pods': typeof ReportsPendingPodsRoute
  '/reports/transit-eway-bill': typeof ReportsTransitEwayBillRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dispatch': typeof DispatchRoute
  '/dispatch-orders': typeof DispatchOrdersRoute
  '/freight-billing': typeof FreightBillingRoute
  '/insurance-claim-tracking': typeof InsuranceClaimTrackingRoute
  '/invoice-load-details': typeof InvoiceLoadDetailsRoute
  '/order-info': typeof OrderInfoRoute
  '/segment-info': typeof SegmentInfoRoute
  '/service-level': typeof ServiceLevelRoute
  '/shipment-details': typeof ShipmentDetailsRoute
  '/transit-damage-info': typeof TransitDamageInfoRoute
  '/transit-info': typeof TransitInfoRoute
  '/user-creation': typeof UserCreationRoute
  '/vehicle-info': typeof VehicleInfoRoute
  '/reports/freight-bills': typeof ReportsFreightBillsRoute
  '/reports/pending-pods': typeof ReportsPendingPodsRoute
  '/reports/transit-eway-bill': typeof ReportsTransitEwayBillRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dispatch'
    | '/dispatch-orders'
    | '/freight-billing'
    | '/insurance-claim-tracking'
    | '/invoice-load-details'
    | '/order-info'
    | '/segment-info'
    | '/service-level'
    | '/shipment-details'
    | '/transit-damage-info'
    | '/transit-info'
    | '/user-creation'
    | '/vehicle-info'
    | '/reports/freight-bills'
    | '/reports/pending-pods'
    | '/reports/transit-eway-bill'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dispatch'
    | '/dispatch-orders'
    | '/freight-billing'
    | '/insurance-claim-tracking'
    | '/invoice-load-details'
    | '/order-info'
    | '/segment-info'
    | '/service-level'
    | '/shipment-details'
    | '/transit-damage-info'
    | '/transit-info'
    | '/user-creation'
    | '/vehicle-info'
    | '/reports/freight-bills'
    | '/reports/pending-pods'
    | '/reports/transit-eway-bill'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/dispatch'
    | '/dispatch-orders'
    | '/freight-billing'
    | '/insurance-claim-tracking'
    | '/invoice-load-details'
    | '/order-info'
    | '/segment-info'
    | '/service-level'
    | '/shipment-details'
    | '/transit-damage-info'
    | '/transit-info'
    | '/user-creation'
    | '/vehicle-info'
    | '/reports/freight-bills'
    | '/reports/pending-pods'
    | '/reports/transit-eway-bill'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DispatchRoute: typeof DispatchRoute
  DispatchOrdersRoute: typeof DispatchOrdersRoute
  FreightBillingRoute: typeof FreightBillingRoute
  InsuranceClaimTrackingRoute: typeof InsuranceClaimTrackingRoute
  InvoiceLoadDetailsRoute: typeof InvoiceLoadDetailsRoute
  OrderInfoRoute: typeof OrderInfoRoute
  SegmentInfoRoute: typeof SegmentInfoRoute
  ServiceLevelRoute: typeof ServiceLevelRoute
  ShipmentDetailsRoute: typeof ShipmentDetailsRoute
  TransitDamageInfoRoute: typeof TransitDamageInfoRoute
  TransitInfoRoute: typeof TransitInfoRoute
  UserCreationRoute: typeof UserCreationRoute
  VehicleInfoRoute: typeof VehicleInfoRoute
  ReportsFreightBillsRoute: typeof ReportsFreightBillsRoute
  ReportsPendingPodsRoute: typeof ReportsPendingPodsRoute
  ReportsTransitEwayBillRoute: typeof ReportsTransitEwayBillRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-info': {
      id: '/vehicle-info'
      path: '/vehicle-info'
      fullPath: '/vehicle-info'
      preLoaderRoute: typeof VehicleInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-creation': {
      id: '/user-creation'
      path: '/user-creation'
      fullPath: '/user-creation'
      preLoaderRoute: typeof UserCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transit-info': {
      id: '/transit-info'
      path: '/transit-info'
      fullPath: '/transit-info'
      preLoaderRoute: typeof TransitInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transit-damage-info': {
      id: '/transit-damage-info'
      path: '/transit-damage-info'
      fullPath: '/transit-damage-info'
      preLoaderRoute: typeof TransitDamageInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment-details': {
      id: '/shipment-details'
      path: '/shipment-details'
      fullPath: '/shipment-details'
      preLoaderRoute: typeof ShipmentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-level': {
      id: '/service-level'
      path: '/service-level'
      fullPath: '/service-level'
      preLoaderRoute: typeof ServiceLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segment-info': {
      id: '/segment-info'
      path: '/segment-info'
      fullPath: '/segment-info'
      preLoaderRoute: typeof SegmentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-info': {
      id: '/order-info'
      path: '/order-info'
      fullPath: '/order-info'
      preLoaderRoute: typeof OrderInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-load-details': {
      id: '/invoice-load-details'
      path: '/invoice-load-details'
      fullPath: '/invoice-load-details'
      preLoaderRoute: typeof InvoiceLoadDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-claim-tracking': {
      id: '/insurance-claim-tracking'
      path: '/insurance-claim-tracking'
      fullPath: '/insurance-claim-tracking'
      preLoaderRoute: typeof InsuranceClaimTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight-billing': {
      id: '/freight-billing'
      path: '/freight-billing'
      fullPath: '/freight-billing'
      preLoaderRoute: typeof FreightBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch-orders': {
      id: '/dispatch-orders'
      path: '/dispatch-orders'
      fullPath: '/dispatch-orders'
      preLoaderRoute: typeof DispatchOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/transit-eway-bill': {
      id: '/reports/transit-eway-bill'
      path: '/reports/transit-eway-bill'
      fullPath: '/reports/transit-eway-bill'
      preLoaderRoute: typeof ReportsTransitEwayBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/pending-pods': {
      id: '/reports/pending-pods'
      path: '/reports/pending-pods'
      fullPath: '/reports/pending-pods'
      preLoaderRoute: typeof ReportsPendingPodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/freight-bills': {
      id: '/reports/freight-bills'
      path: '/reports/freight-bills'
      fullPath: '/reports/freight-bills'
      preLoaderRoute: typeof ReportsFreightBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DispatchRoute: DispatchRoute,
  DispatchOrdersRoute: DispatchOrdersRoute,
  FreightBillingRoute: FreightBillingRoute,
  InsuranceClaimTrackingRoute: InsuranceClaimTrackingRoute,
  InvoiceLoadDetailsRoute: InvoiceLoadDetailsRoute,
  OrderInfoRoute: OrderInfoRoute,
  SegmentInfoRoute: SegmentInfoRoute,
  ServiceLevelRoute: ServiceLevelRoute,
  ShipmentDetailsRoute: ShipmentDetailsRoute,
  TransitDamageInfoRoute: TransitDamageInfoRoute,
  TransitInfoRoute: TransitInfoRoute,
  UserCreationRoute: UserCreationRoute,
  VehicleInfoRoute: VehicleInfoRoute,
  ReportsFreightBillsRoute: ReportsFreightBillsRoute,
  ReportsPendingPodsRoute: ReportsPendingPodsRoute,
  ReportsTransitEwayBillRoute: ReportsTransitEwayBillRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
