/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportationRouteImport } from './routes/transportation'
import { Route as OutboundRouteImport } from './routes/outbound'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as InboundIndexRouteImport } from './routes/inbound.index'
import { Route as InboundPutawayRouteImport } from './routes/inbound.putaway'
import { Route as InboundAsnRouteImport } from './routes/inbound.asn'
import { Route as InboundDeliveryIdRouteImport } from './routes/inbound.delivery.$id'

const TransportationRoute = TransportationRouteImport.update({
  id: '/transportation',
  path: '/transportation',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundRoute = OutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundIndexRoute = InboundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboundRoute,
} as any)
const InboundPutawayRoute = InboundPutawayRouteImport.update({
  id: '/putaway',
  path: '/putaway',
  getParentRoute: () => InboundRoute,
} as any)
const InboundAsnRoute = InboundAsnRouteImport.update({
  id: '/asn',
  path: '/asn',
  getParentRoute: () => InboundRoute,
} as any)
const InboundDeliveryIdRoute = InboundDeliveryIdRouteImport.update({
  id: '/delivery/$id',
  path: '/delivery/$id',
  getParentRoute: () => InboundRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbound': typeof InboundRouteWithChildren
  '/outbound': typeof OutboundRoute
  '/transportation': typeof TransportationRoute
  '/inbound/asn': typeof InboundAsnRoute
  '/inbound/putaway': typeof InboundPutawayRoute
  '/inbound/': typeof InboundIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/inbound/delivery/$id': typeof InboundDeliveryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/outbound': typeof OutboundRoute
  '/transportation': typeof TransportationRoute
  '/inbound/asn': typeof InboundAsnRoute
  '/inbound/putaway': typeof InboundPutawayRoute
  '/inbound': typeof InboundIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/inbound/delivery/$id': typeof InboundDeliveryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbound': typeof InboundRouteWithChildren
  '/outbound': typeof OutboundRoute
  '/transportation': typeof TransportationRoute
  '/inbound/asn': typeof InboundAsnRoute
  '/inbound/putaway': typeof InboundPutawayRoute
  '/inbound/': typeof InboundIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/inbound/delivery/$id': typeof InboundDeliveryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbound'
    | '/outbound'
    | '/transportation'
    | '/inbound/asn'
    | '/inbound/putaway'
    | '/inbound/'
    | '/reports/'
    | '/inbound/delivery/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/outbound'
    | '/transportation'
    | '/inbound/asn'
    | '/inbound/putaway'
    | '/inbound'
    | '/reports'
    | '/inbound/delivery/$id'
  id:
    | '__root__'
    | '/'
    | '/inbound'
    | '/outbound'
    | '/transportation'
    | '/inbound/asn'
    | '/inbound/putaway'
    | '/inbound/'
    | '/reports/'
    | '/inbound/delivery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboundRoute: typeof InboundRouteWithChildren
  OutboundRoute: typeof OutboundRoute
  TransportationRoute: typeof TransportationRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportation': {
      id: '/transportation'
      path: '/transportation'
      fullPath: '/transportation'
      preLoaderRoute: typeof TransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound': {
      id: '/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof OutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/': {
      id: '/inbound/'
      path: '/'
      fullPath: '/inbound/'
      preLoaderRoute: typeof InboundIndexRouteImport
      parentRoute: typeof InboundRoute
    }
    '/inbound/putaway': {
      id: '/inbound/putaway'
      path: '/putaway'
      fullPath: '/inbound/putaway'
      preLoaderRoute: typeof InboundPutawayRouteImport
      parentRoute: typeof InboundRoute
    }
    '/inbound/asn': {
      id: '/inbound/asn'
      path: '/asn'
      fullPath: '/inbound/asn'
      preLoaderRoute: typeof InboundAsnRouteImport
      parentRoute: typeof InboundRoute
    }
    '/inbound/delivery/$id': {
      id: '/inbound/delivery/$id'
      path: '/delivery/$id'
      fullPath: '/inbound/delivery/$id'
      preLoaderRoute: typeof InboundDeliveryIdRouteImport
      parentRoute: typeof InboundRoute
    }
  }
}

interface InboundRouteChildren {
  InboundAsnRoute: typeof InboundAsnRoute
  InboundPutawayRoute: typeof InboundPutawayRoute
  InboundIndexRoute: typeof InboundIndexRoute
  InboundDeliveryIdRoute: typeof InboundDeliveryIdRoute
}

const InboundRouteChildren: InboundRouteChildren = {
  InboundAsnRoute: InboundAsnRoute,
  InboundPutawayRoute: InboundPutawayRoute,
  InboundIndexRoute: InboundIndexRoute,
  InboundDeliveryIdRoute: InboundDeliveryIdRoute,
}

const InboundRouteWithChildren =
  InboundRoute._addFileChildren(InboundRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboundRoute: InboundRouteWithChildren,
  OutboundRoute: OutboundRoute,
  TransportationRoute: TransportationRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
